package me.herrlestrate.yandexintro.Parser;

import org.json.JSONObject;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.io.File;
import java.io.FileNotFoundException;
import java.net.URL;
import java.util.Scanner;

import static org.junit.Assert.*;

public class CustomParserTest {

    @Before
    public void setUp() throws Exception {
    }

    @After
    public void tearDown() throws Exception {
    }

    /**
     * Эти тесты ловят ошибку при проверке на валидность строки
     * Поэтому, файл не создаётся. В логгере пишется какая именно причина.
     */
    @Test
    public void parseTo_FileNotFound() {
        File[] files = getResourceFolderFiles("FileNotFound");
        CustomParser customParser;
        for(int i = 0; i < files.length; i++){
            customParser = new CustomParser(files[i].getAbsolutePath());
            customParser.parseTo("test-output.json");
            File file = new File("test-output.json");
            if(file.exists()){
                fail("[FileNotFound] File exists, but it is error! Test " + (i+1));
                if(!file.delete()){
                    System.err.println("Error while delete file!");
                }
            } else {
                assertTrue("[FileNotFound] #" + (i+1) + " Ok!",true);
            }
        }
    }

    //

    /**
     * Эти тесты ловят успешный парсинг
     * Json'ы сравниваются по внутреннему содержимому, а не по строчкам
     */
    @Test
    public void parseTo_Success() {
        File[] files = getResourceFolderFiles("Success_Input");
        File[] output = getResourceFolderFiles("Success_Output");
        CustomParser customParser;
        for(int i = 0;i < files.length; i++){
            if(!output[i].exists()){
                System.err.println("For test " + (i+1) + " answer-output not founded!");
                continue;
            }
            customParser = new CustomParser(files[i].getAbsolutePath());
            File jOutput = new File("test-output.json");
            try {
                if (jOutput.exists() && !jOutput.delete()) {
                    System.err.println("Some errors with test-output.json");
                    fail("Cannot delete test-output.json");
                }
            }catch(SecurityException ex){
                ex.printStackTrace();
            }
            customParser.parseTo("test-output.json");
            boolean result = compare(output[i], jOutput);
            assertTrue(result);
            if (jOutput.exists() && !jOutput.delete()) {
            }
        }
    }

    private boolean compare(File answer, File result){
        Scanner scanner;
        StringBuilder sbAnswer = new StringBuilder();
        StringBuilder sbResult = new StringBuilder();

        try {
            scanner = new Scanner(answer);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
            return false;
        }

        while(scanner.hasNextLine()){
            String s = scanner.nextLine()
                    .toLowerCase();
            sbAnswer.append(s);
        }

        try {
            scanner = new Scanner(result);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
            return false;
        }

        while(scanner.hasNextLine()){
            String s = scanner.nextLine()
                    .toLowerCase();
            sbResult.append(s);
        }

        scanner.close();

        return isJSONObjectEquals(new JSONObject(sbAnswer.toString()),new JSONObject(sbResult.toString()));
    }

    /**
     * @param answer from source output file
     * @param result generated by parseTo method
     * @return is equals answer and result
     */
    private boolean isJSONObjectEquals(JSONObject answer, JSONObject result){
        return result.similar(answer);
    }

    //

    private File[] getResourceFolderFiles(String folder){
        URL url = getClass().getClassLoader().getResource(folder);
        String path = url.getPath();
        return new File(path).listFiles();
    }
}